config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/contact'
  get 'articles/index'
  get 'homepage/home'
  get '/articles', to: 'articles#index', as: 'articles'
  get '/contact', to: 'static_pages#contact'
  resources :articles
  resources :posts
  resources :projects
  root 'homepage#home'  # Adjusted to point to the 'home' action in HomepageController

  # ... other routes ...

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  attribute :name, :text
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def show
    @article = Article.find_by(id: params[:id])

  if @article.nil?
    # Handle the case where the article is not found, e.g., redirect to the root path.
    redirect_to_custom_root_path
  end
  end


private

  def redirect_to_custom_root_path
    redirect_to articles_path, alert: "Article not found"
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def home
    @posts = Post.all.limit(3).order('created_at desc')
    @projects = Project.all.limit(3).order('created_at desc')

  end

  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.paginate(page: params[:page], per_page: 10) # Adjust per_page as needed
  end

  def new
      @post = Post.new
  end

  def create
    @post = Post.new post_params

    if @post.save
      redirect_to post_url(@post), notice: "Hello yeah, Abdoul! Your post is successfully saved"
    else
      render "new", alert: "Oh no, Abdoul! I was unable to save your post."
    end
  end

    def show
      @post = Post.find_by!(slug: params[:id])
      @articles = Post.where.not(id: @post.id).order('created_at DESC').limit(5)
    end


  def edit
    @post = Post.find(params[:id])

  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post), notice: "Zuuuuuuuuh! Your post was successfully saved!"
  end




  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path, notice: "Post was successfully destroyed."
    else
      # Log an error or handle the failure appropriately
      flash[:alert] = "Failed to destroy the post."
      redirect_to posts_path
    end
  end

  def find_project
    @post = Post.friendly.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all.order('created_at desc')
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: "Nice Abdoul! That project was successfully saved!"
    else
      render 'new'
    end
  end

  def show
    @project = Project.find_by(slug: params[:id])
    if @project.nil?
      # Handle the case where the project is not found by redirecting to the root path.
      redirect_to root_path
      return
    end
  end




  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])

  end

  def update
    if @project.update project_params
      redirect_to @project, notice: "Nice Abdoul! That project was successfully updated!"
    else
      render 'edit'
    end

  end

  def destroy

  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :link)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abdoul Kane - Part Service Designer, Part Developer</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  <link rel="stylesheet" href="css/application.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  <link rel="stylesheet" href="css/application.css">
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>

<header id="main_navigation" class="clearfix">
  <span class="name">Abdoul Kane</span>
  <nav>
    <a href="<%= articles_path %>">Articles</a>
    <a href="<%= projects_path %>">Projects</a>
    <a href="<%= contact_path %>">Contact</a>
  </nav>
</header>




<div class="pagination">
  <span class="previous_page disabled">Previous</span>
  <em class="current">1</em>
  <a rel="next" href="#">2</a>
  <a class="next_page" href="#">next</a>
  </div>
</div>


<footer id="main_footer">
<p class="copyright">&copy; 2023
Abdoul Kane</p>
<nav>
  <a href="https://github.com/zizsalam" target="_blank"><i class="fa-brands fa-square-github"></i></a>
  <a href="https://twitter.com/home" target="_blank"><i class="fa-brands fa-twitter"></i></a>
  <a href="https://medium.com/@kaneaziz" target="_blank"><i class="fa-brands fa-medium"></i></a>
</nav>
</footer>

</body>

</html>

app/views/homepage/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abdoul Kane - Part Service Designer, Part Developer</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">


</head>
<body>


<div class="wrapper clearfix wrapper_padding "> <!-- Move the wrapper inside the body and correct the class -->
  <div class="col-1 about homepage_content"> <!-- Remove the dot before the class name -->
    <h2>About</h2>
    <hr>
    <p>I am service designer & developer living in Winterthur Switzerland.</p>
    <p>By day I work as a service designer at Medic, by night contribute on open source and personal design & code rails, javascript, html/css </p>
    <p>You can find me speaking on Twitter, swooshing some pixel on Dribbble, and sharing some code on Github.</p>
  </div>
  <div class="col-2 homepage_content">
  <h2>Stuff I've Written</h2>
  <hr>
  <%  @posts.each do |post| %>
      <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
       <h3><a href="#"><%= link_to post.title, post %></a></h3>
  <% end %>

</div>
  <div class="col-3 homepage_content">
  <h2>Stuff I've Built</h2>
  <hr>
   <%  @projects.each do |project| %>
        <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
       <h3><a href="#"><%= link_to project.title, project %></a></h3>
  <% end %>
  <hr>
  </div>
</div>



</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<%= javascript_include_tag 'rails-ujs' %>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap" rel="stylesheet">
    <title>MyPortfolioSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

     <header id="main_navigation" class="clearfix">
  <%= link_to "Abdoul Kane", root_path, class: "name" %>
  <nav>
    <%= link_to "Articles", posts_path %>
    <%= link_to "Projects", projects_path %>
    <%= link_to "Contact", contact_path %>
  </nav>
</header>

    <%= yield %>

<footer id="main_footer">
<p class="copyright">&copy; 2023
Abdoul Kane</p>
<nav>
  <a href="https://github.com/zizsalam" target="_blank"><i class="fa-brands fa-square-github"></i></a>
  <a href="https://twitter.com/home" target="_blank"><i class="fa-brands fa-twitter"></i></a>
  <a href="https://medium.com/@kaneaziz" target="_blank"><i class="fa-brands fa-medium"></i></a>
</nav>
</footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prevent this post from saving:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content, "Write your article here" %><br>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="page_title">Stuff I've Written</h1>
<div id="posts_wrapper" class="skinny_wrapper">
  <% @posts.each do |post| %>
    <div class="post">
      <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
      <h2><%= link_to post.title, post %></h2>
      <hr>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>New Posts</h1>
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="
skinny_wrapper wrapper_padding">
  <header>
  <p class="date"><% @post.created_at.strftime('%A, %B %d') %></p>
  <h1> <%= @post.title %></h1>
  <hr>
  </header>

  <div id="content">
  <%= simple_format @post.content %>
  </div>

  <hr>

  <div id="share_box">
    <p>Share The Article</p>
    <a href="https://github.com/zizsalam" target="_blank"><i class="fa-brands fa-square-github"></i></a>
    <a href="https://twitter.com/home" target="_blank"><i class="fa-brands fa-twitter"></i></a>
    <a href="https://medium.com/@kaneaziz" target="_blank"><i class="fa-brands fa-medium"></i></a>
  </div>

  <hr>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'link' %>


</div>

app/views/projects/_form.html.erb
<%= form_with(model: @project, local: true) do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prevent this project from saving:</h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <br>
  <br>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <br>
  <br>

 <%= form.label :link %><br>
<%= form.text_field :link, id: 'project_link' %>

  <br>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>Edit Project</h1>
<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<% if @project %>
  <div class="skinny_wrapper wrapper_padding">
    <header>
      <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
      <p><%= @project.title %></p>
      <hr>
    </header>
    <!-- Other project details here -->
  </div>
<% else %>
  <p>Project not found</p>
<% end %>
<h1 id="page_title">Stuff I've Built</h1>
<div id="projects_wrapper" class="skinny_wrapper">
  <% @projects.each do |project| %>
    <div class="project">
      <p class="date"><%= project.created_at.strftime("%A, %B %d") %></p>
      <h2><%= link_to project.title, project %></h2>
      <hr>
   <div id="name">
  <%= simple_format @project.description %>
</div>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>New Project</h1>
<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="project_show_content"  class="
skinny_wrapper wrapper_padding">
  <header>
  <p class="date"><% @project.created_at.strftime('%A, %B %d') %></p>
  <h1> <%= @project.title %></h1>
  <hr>
  </header>

  <div id="description">
  <%= simple_format @project.description %>
  </div>

  <hr>

  <div id="share_box">
    <p>Share The Project</p>
    <a href="https://github.com/zizsalam" target="_blank"><i class="fa-brands fa-square-github"></i></a>
    <a href="https://twitter.com/home" target="_blank"><i class="fa-brands fa-twitter"></i></a>
    <a href="https://medium.com/@kaneaziz" target="_blank"><i class="fa-brands fa-medium"></i></a>
  </div>

  <hr>
<%= link_to "Delete", @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'link' %>


</div>

app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abdoul Kane - Part Service Designer, Part Developer</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  <link rel="stylesheet" href="css/application.css">
  <link rel="stylesheet" href="css/application.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  <link rel="stylesheet" href="css/application.css">
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>



<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
  <label>Name</label><br>
  <input type="text">

  <br>

  <label>Email</label>
  <input type="text">

  <br>

  <label>Message</label><br>
  <textarea></textarea>

  <br>

  <input type="submit" value="Send Message"
  class="button">
</div>






</body>

</html>